---
language: "php"

php:
  - 7.1

before_script:
- composer install
- composer require phpunit/phpunit satooshi/php-coveralls
- wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.6.0/php-cs-fixer.phar -O php-cs-fixer
- chmod +x ./php-cs-fixer
- mkdir -p tests/coverage

script:
- ./php-cs-fixer fix --dry-run --diff
- phpunit --coverage-text --coverage-clover ./tests/coverage/clover.xml

after_script:
- travis_retry php vendor/bin/coveralls -v
